apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
  labels:
    app: django-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
      - name: django-app
        image: django-app
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
          - name: DB_HOST
            value: "192.168.99.1"
          - name: DB
            value: "postgres"
          - name: DB_USER
            value: "postgres"
          - name: DB_PORT
            value: "54320"
