apiVersion: v1
kind: Service
metadata:
  name: django-app
  labels:
    name: django-app
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: django-app
